### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble_docs_archived#21]
1. Build -> User Interface -> Page Structure - out of date. Please update it and add more details like ViewGroups etc. 
2. Build -> User Interface -> Widgets - out of date. Just add the Widget Reference page here, 
3. Build -> User Interface -> Layout - out of date. Just add the Widget Reference page's layout section
4. Build -> User Interface -> Handle Data - all sub-pages are really weak with some copy/paste from kitchen sink. Please add more details and structure them properly. For APIs, provide the list of options like you did for the widgets. Give examples.
5. Build -> User Interface -> Make it interactive with actions. seems like another copy paste stuff. Please fix it and structure it properly with details and examples
6. https://docs.ensembleui.com/#/test/1-preview-app link to the iOS app is out of date and wrong. QR code may be wrong as well
7. At the bottom, just like you have Widget Reference, add the following - Action Reference, API reference, Javascript Reference
8. We need a special page devoted to creating custom widgets. This is entirely missing from the documentation.

**Comment by sibteali786** [comment]
@kmahmood74 some queries
1. Can you suggest a bit more of what should be added to the page structure in Build -> User Interface, like body, header, and menu are already there so what other general widgets we can add here? And i could not understand ViewGroups either.
2. From what i understood widget reference page should replace the Widgets page in User Interface as it has more details the current widgets page in User Interface.
3. Layout section from the widget reference only contains properties with their usage but no examples of yaml. So just confirming if its fine,
after refining these i ll move on to other sections.

**Comment by kmahmood74** [comment]
what are the properties of the header and menu, list them the way you have listed other widgets. Give examples of different types or menus and different types of headers. Use your judgement and make it like you are talking to a new person. 

ViewGroups - learn them if you don't know. It's not rocket science :-) there are kitchen sink examples. 

Layout and Widgets - reference + examples. For the reference, you can just put a link to the reference. 

Use your judgement on all these. I am sure you will figure it out

**Comment by sibteali786** [comment]
Thank you @kmahmood74 . Sure i can do that.

**Comment by sibteali786** [comment]
preview at [ensemble docs](https://ensemble-docs-ff195.web.app) @kmahmood74

**Comment by sibteali786** [comment]
@kmahmood74 i was thinking if we can have page named like " Tips and Tricks" where we can gives examples of customizations like for example custom icons for the bottomNavBar where we can use profile picture as NavBar icon instead of a simple icon . 
what are your thoughts on this ? because for now in the page structure dealing with all of this might not be a good idea as its already much information there

**Comment by kmahmood74** [comment]
Yes that makes sense. Please go ahead
