### ISSUE TITLE
The example links under Menu give 404 errors

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble_docs_archived#39]
@sibteali786 go here https://docs.ensembleui.com/#/build/user-interface/1-page-structure?id=menu

and click on links where it says example here. It points to non-existant apps. 

These examples are there in kitchen sink, please fix the links. Also check links everywhere as this issue may be prevalent through out

**Comment by sibteali786** [comment]
the links are valid though i have them all inside my own copy of Ensemble Kitchen Sink, let me fix it in a moment.
