### ISSUE TITLE
create a separate top level section for how to call APIs and handle responses

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble_docs_archived#44]
A separate top level menu item called APIs. This should have subections just like you have for Actions

index - what is invokeAPI action and javascript. 
Headers - how to set headers including authorization header. Very common question
REST APIs - how to call REST APIs and handle JSON responses
graphQL APIs - how to call graphQL APIs with queries and handle graphQL responses - ask @sharjeelyunus for help
Errors - how to handle errors
Bind to templates - how to bind APIs to item-templates
Calling Multiple APIs (API Chaining) - how to call multiple APIs (API chaining). Should

**Comment by sharjeelyunus** [comment]
add Parameters as well
