### ISSUE TITLE
Camera permission

### ISSUE THREAD

**Issue by snehmehta** [EnsembleUI/ensemble_docs_archived#51]
https://docs.ensembleui.com/#/actions/3-openCamera?id=action-opencamera

For IOS, camera permission are required to be added inside of info.plist ( found inside <project-name>/ios/Runner/Info.plist) 

```
	<key>NSCameraUsageDescription</key>
	<string> <Specify reason> </string>
	<key>NSMicrophoneUsageDescription</key>
	<string> <Specify reason>  </string>
	
	<!-- if allowGalleryPicker is set to true -->
	<key>NSPhotoLibraryUsageDescription</key>
	<string> <Specify reason>  </string>
```

**Comment by RuthLHanan** [comment]
Add in minCount, allowing users to set a minimum image capture requirement. Users can specify the storage type with type=${ensemble.storage}. Upon capturing the designated number of images (defined by maxCount), the camera will automatically close

**Comment by kmahmood74** [comment]
this should be documented

**Comment by RuthLHanan** [comment]
documented min/max count with type=${ensemble.storage.xyz}, but I didn't do anything with "camera permission are required to be added inside of info.plist"
