### ISSUE TITLE
Document Device Capabilities

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble_docs_archived#64]
We need a separate section at the top level menu - "Accessing Device Capabilities"

This should include all the device capabilities we expose. For a quick list, see the Device Capabilities section on the Kitchen Sink app. 

You can simply reference the actions etc that are already documented under actions and events. OK to repeat the links but not the actual content.

**Comment by RuthLHanan** [comment]
good to go 😎
